- name: install nginx
  yum: 
    name:
      - nginx
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: start nginx service 
  systemd:
    name: nginx
    state: started
  become: true

- name: deploy index
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    become: true

